Repository OpenVicProject/OpenVic-Simulation, pull requests merged in 2023-12, with the labels that each got.

#87 Dataloading Country History - Part 2
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/dataloader/NodeTools.hpp
  src/openvic-simulation/history/CountryHistory.cpp
  src/openvic-simulation/history/CountryHistory.hpp
  src/openvic-simulation/research/Invention.hpp
  src/openvic-simulation/research/Technology.hpp
Labels: enhancement

#45 Skeleton Event Loading
  src/openvic-simulation/GameManager.hpp
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/dataloader/Dataloader.hpp
  src/openvic-simulation/misc/Event.cpp
  src/openvic-simulation/misc/Event.hpp
Labels: enhancement

#90 Decision dataloading (kind of)
  src/openvic-simulation/GameManager.hpp
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/dataloader/Dataloader.hpp
  src/openvic-simulation/misc/Decision.cpp
  src/openvic-simulation/misc/Decision.hpp
Labels: enhancement

#91 Improved identifier registry macro
  src/openvic-simulation/country/Country.cpp
  src/openvic-simulation/country/Country.hpp
  src/openvic-simulation/economy/BuildingType.cpp
  src/openvic-simulation/economy/BuildingType.hpp
  src/openvic-simulation/economy/Good.cpp
  src/openvic-simulation/economy/Good.hpp
  src/openvic-simulation/economy/ProductionType.cpp
  src/openvic-simulation/economy/ProductionType.hpp
  src/openvic-simulation/history/Bookmark.cpp
  src/openvic-simulation/history/Bookmark.hpp
  src/openvic-simulation/interface/GUI.cpp
  src/openvic-simulation/interface/GUI.hpp
  src/openvic-simulation/interface/UI.cpp
  src/openvic-simulation/interface/UI.hpp
  src/openvic-simulation/map/Crime.cpp
  src/openvic-simulation/map/Crime.hpp
  src/openvic-simulation/map/Map.cpp
  src/openvic-simulation/map/Map.hpp
  src/openvic-simulation/map/Province.hpp
  src/openvic-simulation/map/TerrainType.cpp
  src/openvic-simulation/map/TerrainType.hpp
  src/openvic-simulation/military/Deployment.cpp
  src/openvic-simulation/military/Deployment.hpp
  src/openvic-simulation/military/LeaderTrait.cpp
  src/openvic-simulation/military/LeaderTrait.hpp
  src/openvic-simulation/military/Unit.cpp
  src/openvic-simulation/military/Unit.hpp
  src/openvic-simulation/military/Wargoal.cpp
  src/openvic-simulation/military/Wargoal.hpp
  src/openvic-simulation/misc/Decision.cpp
  src/openvic-simulation/misc/Decision.hpp
  src/openvic-simulation/misc/Define.cpp
  src/openvic-simulation/misc/Define.hpp
  src/openvic-simulation/misc/Event.cpp
  src/openvic-simulation/misc/Event.hpp
  src/openvic-simulation/misc/Modifier.cpp
  src/openvic-simulation/misc/Modifier.hpp
  src/openvic-simulation/politics/Government.cpp
  src/openvic-simulation/politics/Government.hpp
  src/openvic-simulation/politics/Ideology.cpp
  src/openvic-simulation/politics/Ideology.hpp
  src/openvic-simulation/politics/Issue.cpp
  src/openvic-simulation/politics/Issue.hpp
  src/openvic-simulation/politics/NationalFocus.cpp
  src/openvic-simulation/politics/NationalFocus.hpp
  src/openvic-simulation/politics/NationalValue.cpp
  src/openvic-simulation/politics/NationalValue.hpp
  src/openvic-simulation/politics/Rebel.cpp
  src/openvic-simulation/politics/Rebel.hpp
  src/openvic-simulation/pop/Culture.cpp
  src/openvic-simulation/pop/Culture.hpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/Pop.hpp
  src/openvic-simulation/pop/Religion.cpp
  src/openvic-simulation/pop/Religion.hpp
  src/openvic-simulation/research/Invention.cpp
  src/openvic-simulation/research/Invention.hpp
  src/openvic-simulation/research/Technology.cpp
  src/openvic-simulation/research/Technology.hpp
  src/openvic-simulation/types/IdentifierRegistry.hpp
Labels: enhancement

#89 Pop History Loading (with the new system)
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/dataloader/Dataloader.hpp
  src/openvic-simulation/history/Bookmark.cpp
  src/openvic-simulation/history/Bookmark.hpp
  src/openvic-simulation/history/CountryHistory.cpp
  src/openvic-simulation/history/CountryHistory.hpp
  src/openvic-simulation/history/HistoryMap.cpp
  src/openvic-simulation/history/HistoryMap.hpp
  src/openvic-simulation/history/ProvinceHistory.cpp
  src/openvic-simulation/history/ProvinceHistory.hpp
  src/openvic-simulation/interface/UI.hpp
  src/openvic-simulation/map/Map.cpp
  src/openvic-simulation/map/Province.cpp
  src/openvic-simulation/map/Province.hpp
  src/openvic-simulation/misc/Decision.cpp
  src/openvic-simulation/politics/Government.cpp
  src/openvic-simulation/politics/Government.hpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/Pop.hpp
  src/openvic-simulation/types/fixed_point/FixedPoint.hpp
Labels: enhancement

#96 Calculate distance between adjacencies
  src/openvic-simulation/map/Map.cpp
  src/openvic-simulation/map/Province.cpp
  src/openvic-simulation/map/Province.hpp
Labels: enhancement

#97 Made pop type strata moddable
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/dataloader/Dataloader.hpp
  src/openvic-simulation/economy/Good.cpp
  src/openvic-simulation/economy/Good.hpp
  src/openvic-simulation/military/Unit.cpp
  src/openvic-simulation/military/Unit.hpp
  src/openvic-simulation/misc/Modifier.cpp
  src/openvic-simulation/misc/Modifier.hpp
  src/openvic-simulation/politics/Rebel.cpp
  src/openvic-simulation/politics/Rebel.hpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/Pop.hpp
  src/openvic-simulation/research/Technology.cpp
  src/openvic-simulation/research/Technology.hpp
Labels: enhancement

#92 on_action dataloading
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/misc/Event.cpp
  src/openvic-simulation/misc/Event.hpp
Labels: enhancement

#98 Additional adjacency loading
  src/openvic-simulation/GameManager.cpp
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/economy/BuildingType.cpp
  src/openvic-simulation/economy/BuildingType.hpp
  src/openvic-simulation/history/ProvinceHistory.cpp
  src/openvic-simulation/map/Map.cpp
  src/openvic-simulation/map/Map.hpp
  src/openvic-simulation/map/Province.cpp
  src/openvic-simulation/map/Province.hpp
  src/openvic-simulation/types/Vector.hpp
Labels: enhancement

#102 Fixed TGC compatibility + misc cleanup
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/economy/Good.cpp
  src/openvic-simulation/history/DiplomaticHistory.cpp
  src/openvic-simulation/interface/GFX.cpp
  src/openvic-simulation/interface/GFX.hpp
  src/openvic-simulation/interface/GUI.cpp
  src/openvic-simulation/interface/GUI.hpp
  src/openvic-simulation/map/Map.cpp
  src/openvic-simulation/military/Unit.cpp
  src/openvic-simulation/misc/Decision.cpp
  src/openvic-simulation/misc/Decision.hpp
  src/openvic-simulation/misc/Event.cpp
  src/openvic-simulation/misc/Event.hpp
  src/openvic-simulation/misc/Modifier.cpp
Labels: bug, enhancement

#100 Change colour_t to be a strongly typed structure
  src/openvic-simulation/GameManager.cpp
  src/openvic-simulation/country/Country.cpp
  src/openvic-simulation/dataloader/NodeTools.cpp
  src/openvic-simulation/dataloader/NodeTools.hpp
  src/openvic-simulation/economy/Good.cpp
  src/openvic-simulation/interface/GFX.cpp
  src/openvic-simulation/interface/GFX.hpp
  src/openvic-simulation/interface/UI.cpp
  src/openvic-simulation/interface/UI.hpp
  src/openvic-simulation/map/Map.cpp
  src/openvic-simulation/map/Map.hpp
  src/openvic-simulation/map/Province.cpp
  src/openvic-simulation/map/Region.cpp
  src/openvic-simulation/map/TerrainType.cpp
  src/openvic-simulation/politics/Ideology.cpp
  src/openvic-simulation/pop/Culture.cpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/Religion.cpp
  src/openvic-simulation/types/Colour.hpp
  src/openvic-simulation/types/IdentifierRegistry.cpp
  src/openvic-simulation/types/IdentifierRegistry.hpp
  src/openvic-simulation/utility/BMP.cpp
  src/openvic-simulation/utility/Getters.hpp
  src/openvic-simulation/utility/Utility.hpp
Labels: enhancement

#104 Add `BMP::palette_colour_t` as uint32_t
  src/openvic-simulation/utility/BMP.cpp
  src/openvic-simulation/utility/BMP.hpp
Labels: bug

#103 Province building scaffolding
  src/openvic-simulation/GameManager.cpp
  src/openvic-simulation/GameManager.hpp
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/economy/BuildingInstance.cpp
  src/openvic-simulation/economy/BuildingType.cpp
  src/openvic-simulation/economy/BuildingType.hpp
  src/openvic-simulation/economy/ProductionType.cpp
  src/openvic-simulation/map/Map.cpp
  src/openvic-simulation/map/Map.hpp
  src/openvic-simulation/map/Province.cpp
  src/openvic-simulation/map/Province.hpp
  src/openvic-simulation/types/Date.cpp
  src/openvic-simulation/types/Date.hpp
Labels: enhancement

#108 Dataloading climate and continents
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/map/Map.cpp
  src/openvic-simulation/map/Map.hpp
  src/openvic-simulation/map/Province.cpp
  src/openvic-simulation/map/Province.hpp
  src/openvic-simulation/map/Region.cpp
  src/openvic-simulation/map/Region.hpp
  src/openvic-simulation/map/TerrainType.hpp
Labels: enhancement

#107 Dataloading Issue/Reform Modifiers and RuleSets
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/misc/Modifier.cpp
  src/openvic-simulation/politics/Issue.cpp
  src/openvic-simulation/politics/Issue.hpp
  src/openvic-simulation/politics/PoliticsManager.hpp
Labels: enhancement
