Repository OpenVicProject/OpenVic-Simulation, pull requests merged in 2024-01, with the labels that each got.

#113 Disable AllowShortCompoundRequirementOnASingleLine
  .clang-format
Labels: bug

#112 Added framework for loading all Conditions and Effects
  src/headless/main.cpp
  src/openvic-simulation/GameManager.cpp
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/dataloader/Dataloader.hpp
  src/openvic-simulation/dataloader/NodeTools.cpp
  src/openvic-simulation/dataloader/NodeTools.hpp
  src/openvic-simulation/economy/BuildingInstance.hpp
  src/openvic-simulation/economy/ProductionType.cpp
  src/openvic-simulation/economy/ProductionType.hpp
  src/openvic-simulation/history/CountryHistory.cpp
  src/openvic-simulation/history/DiplomaticHistory.cpp
  src/openvic-simulation/interface/GFX.hpp
  src/openvic-simulation/map/Crime.cpp
  src/openvic-simulation/map/Crime.hpp
  src/openvic-simulation/map/Map.hpp
  src/openvic-simulation/map/State.cpp
  src/openvic-simulation/military/MilitaryManager.hpp
  src/openvic-simulation/military/Wargoal.cpp
  src/openvic-simulation/military/Wargoal.hpp
  src/openvic-simulation/misc/Decision.cpp
  src/openvic-simulation/misc/Decision.hpp
  src/openvic-simulation/misc/Event.cpp
  src/openvic-simulation/misc/Event.hpp
  src/openvic-simulation/misc/Modifier.cpp
  src/openvic-simulation/misc/Modifier.hpp
  src/openvic-simulation/politics/Ideology.cpp
  src/openvic-simulation/politics/Ideology.hpp
  src/openvic-simulation/politics/Issue.cpp
  src/openvic-simulation/politics/Issue.hpp
  src/openvic-simulation/politics/NationalFocus.cpp
  src/openvic-simulation/politics/NationalFocus.hpp
  src/openvic-simulation/politics/Rebel.cpp
  src/openvic-simulation/politics/Rebel.hpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/Pop.hpp
  src/openvic-simulation/research/Invention.cpp
  src/openvic-simulation/research/Invention.hpp
  src/openvic-simulation/research/Technology.cpp
  src/openvic-simulation/research/Technology.hpp
  src/openvic-simulation/scripts/ConditionScript.cpp
  src/openvic-simulation/scripts/ConditionScript.hpp
  src/openvic-simulation/scripts/ConditionalWeight.cpp
  src/openvic-simulation/scripts/ConditionalWeight.hpp
  src/openvic-simulation/scripts/EffectScript.cpp
  src/openvic-simulation/scripts/EffectScript.hpp
  src/openvic-simulation/scripts/Script.hpp
  src/openvic-simulation/types/Colour.hpp
Labels: enhancement

#114 Integer and fixed point squared roots
  src/openvic-simulation/map/Map.cpp
  src/openvic-simulation/map/Map.hpp
  src/openvic-simulation/map/Province.cpp
  src/openvic-simulation/map/Province.hpp
  src/openvic-simulation/types/fixed_point/FixedPoint.hpp
  src/openvic-simulation/utility/NumberUtils.hpp
Labels: bug, enhancement

#101 Add diplomatic actions skeleton
  src/openvic-simulation/GameManager.hpp
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/diplomacy/DiplomacyManager.hpp
  src/openvic-simulation/diplomacy/DiplomaticAction.cpp
  src/openvic-simulation/diplomacy/DiplomaticAction.hpp
  src/openvic-simulation/types/AnyRef.hpp
  src/openvic-simulation/types/FunctionRef.hpp
Labels: enhancement

#116 Mutually exclusive rule groups + modded building rules
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/economy/BuildingType.cpp
  src/openvic-simulation/economy/BuildingType.hpp
  src/openvic-simulation/economy/Good.cpp
  src/openvic-simulation/map/Map.cpp
  src/openvic-simulation/misc/Modifier.cpp
  src/openvic-simulation/politics/Issue.cpp
  src/openvic-simulation/politics/Rule.cpp
  src/openvic-simulation/politics/Rule.hpp
Labels: enhancement

#117 Added expect_item_dictionary_and_default
  src/openvic-simulation/types/IdentifierRegistry.hpp
Labels: enhancement

#118 Added case insensitive ordered set and map and IdentifierRegistry
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/dataloader/NodeTools.hpp
  src/openvic-simulation/dataloader/Vic2PathSearch.cpp
  src/openvic-simulation/scripts/ConditionalWeight.cpp
  src/openvic-simulation/types/IdentifierRegistry.hpp
  src/openvic-simulation/types/OrderedContainers.hpp
  src/openvic-simulation/utility/StringUtils.hpp
Labels: bug, enhancement

#111 Condition definition checking/loading
  src/openvic-simulation/GameManager.hpp
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/dataloader/NodeTools.cpp
  src/openvic-simulation/dataloader/NodeTools.hpp
  src/openvic-simulation/economy/ProductionType.cpp
  src/openvic-simulation/map/Crime.cpp
  src/openvic-simulation/military/Wargoal.cpp
  src/openvic-simulation/misc/Decision.cpp
  src/openvic-simulation/misc/Event.cpp
  src/openvic-simulation/misc/Event.hpp
  src/openvic-simulation/misc/Modifier.cpp
  src/openvic-simulation/politics/Ideology.cpp
  src/openvic-simulation/politics/Issue.cpp
  src/openvic-simulation/politics/NationalFocus.cpp
  src/openvic-simulation/politics/Rebel.cpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/research/Invention.cpp
  src/openvic-simulation/research/Technology.cpp
  src/openvic-simulation/scripts/Condition.cpp
  src/openvic-simulation/scripts/Condition.hpp
  src/openvic-simulation/scripts/ConditionScript.cpp
  src/openvic-simulation/scripts/ConditionScript.hpp
  src/openvic-simulation/scripts/ConditionalWeight.cpp
  src/openvic-simulation/scripts/ConditionalWeight.hpp
  src/openvic-simulation/scripts/ScriptManager.hpp
Labels: enhancement

#123 Added map_callback and expect_item_dictionary_reserve_length
  src/openvic-simulation/country/Country.cpp
  src/openvic-simulation/country/Country.hpp
  src/openvic-simulation/dataloader/Dataloader.hpp
  src/openvic-simulation/dataloader/NodeTools.cpp
  src/openvic-simulation/dataloader/NodeTools.hpp
  src/openvic-simulation/diplomacy/DiplomaticAction.cpp
  src/openvic-simulation/history/CountryHistory.cpp
  src/openvic-simulation/history/ProvinceHistory.cpp
  src/openvic-simulation/map/Map.cpp
  src/openvic-simulation/map/Province.cpp
  src/openvic-simulation/military/Wargoal.cpp
  src/openvic-simulation/misc/Event.cpp
  src/openvic-simulation/misc/Modifier.cpp
  src/openvic-simulation/politics/NationalFocus.cpp
  src/openvic-simulation/politics/NationalFocus.hpp
  src/openvic-simulation/politics/Rebel.cpp
  src/openvic-simulation/politics/Rule.cpp
  src/openvic-simulation/pop/Culture.cpp
  src/openvic-simulation/pop/Culture.hpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/scripts/Condition.cpp
  src/openvic-simulation/types/HasIdentifier.hpp
  src/openvic-simulation/types/IdentifierRegistry.hpp
  src/openvic-simulation/types/OrderedContainers.hpp
Labels: enhancement

#126 Case insensitive modifiers & added more
  src/openvic-simulation/economy/Good.cpp
  src/openvic-simulation/military/Unit.cpp
  src/openvic-simulation/misc/Modifier.cpp
  src/openvic-simulation/misc/Modifier.hpp
  src/openvic-simulation/politics/Rebel.cpp
  src/openvic-simulation/pop/Pop.cpp
Labels: enhancement

#129 Reworked `UniqueKeyRegistry` template params
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/interface/LoadBase.hpp
  src/openvic-simulation/misc/Modifier.cpp
  src/openvic-simulation/misc/Modifier.hpp
  src/openvic-simulation/types/IdentifierRegistry.hpp
Labels: enhancement

#131 Parse missing variables, Logger counting, misc cleanup
  src/headless/main.cpp
  src/openvic-simulation/GameManager.cpp
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/dataloader/NodeTools.hpp
  src/openvic-simulation/diplomacy/DiplomaticAction.hpp
  src/openvic-simulation/economy/BuildingType.cpp
  src/openvic-simulation/economy/ProductionType.cpp
  src/openvic-simulation/economy/ProductionType.hpp
  src/openvic-simulation/history/ProvinceHistory.cpp
  src/openvic-simulation/military/Deployment.cpp
  src/openvic-simulation/military/Deployment.hpp
  src/openvic-simulation/military/Unit.cpp
  src/openvic-simulation/misc/Event.cpp
  src/openvic-simulation/misc/Modifier.cpp
  src/openvic-simulation/politics/Rebel.cpp
  src/openvic-simulation/pop/Culture.cpp
  src/openvic-simulation/pop/Culture.hpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/Pop.hpp
  src/openvic-simulation/research/Invention.cpp
  src/openvic-simulation/types/Colour.hpp
  src/openvic-simulation/types/FunctionRef.hpp
  src/openvic-simulation/types/IdentifierRegistry.hpp
  src/openvic-simulation/utility/Logger.hpp
  src/openvic-simulation/utility/StringUtils.hpp
Labels: enhancement

#119 Add skeleton CountryRelationManager
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/diplomacy/CountryRelation.cpp
  src/openvic-simulation/diplomacy/CountryRelation.hpp
  src/openvic-simulation/diplomacy/DiplomacyManager.hpp
  src/openvic-simulation/diplomacy/DiplomaticAction.cpp
  src/openvic-simulation/diplomacy/DiplomaticAction.hpp
  src/openvic-simulation/utility/ErrorMacros.hpp
  src/openvic-simulation/utility/StringUtils.hpp
  src/openvic-simulation/utility/Utility.hpp
Labels: enhancement

#133 Harmonize empty result behavior for `_search_for_game_path`
  src/openvic-simulation/dataloader/Vic2PathSearch.cpp
  src/openvic-simulation/utility/StringUtils.hpp
Labels: bug, enhancement

#137 Added reserve_more, expect_dictionary_key[s|_map]_reserve_length[_and_default]
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/dataloader/NodeTools.hpp
  src/openvic-simulation/economy/Good.cpp
  src/openvic-simulation/economy/ProductionType.cpp
  src/openvic-simulation/history/Bookmark.cpp
  src/openvic-simulation/history/CountryHistory.cpp
  src/openvic-simulation/history/CountryHistory.hpp
  src/openvic-simulation/history/DiplomaticHistory.cpp
  src/openvic-simulation/history/DiplomaticHistory.hpp
  src/openvic-simulation/history/HistoryManager.hpp
  src/openvic-simulation/history/HistoryMap.hpp
  src/openvic-simulation/history/ProvinceHistory.cpp
  src/openvic-simulation/history/ProvinceHistory.hpp
  src/openvic-simulation/interface/GFX.cpp
  src/openvic-simulation/interface/GFX.hpp
  src/openvic-simulation/interface/UI.cpp
  src/openvic-simulation/map/Map.cpp
  src/openvic-simulation/map/Province.cpp
  src/openvic-simulation/map/Region.cpp
  src/openvic-simulation/map/Region.hpp
  src/openvic-simulation/map/TerrainType.cpp
  src/openvic-simulation/military/LeaderTrait.cpp
  src/openvic-simulation/military/LeaderTrait.hpp
  src/openvic-simulation/military/Wargoal.cpp
  src/openvic-simulation/misc/Decision.cpp
  src/openvic-simulation/misc/Define.cpp
  src/openvic-simulation/misc/Define.hpp
  src/openvic-simulation/misc/Event.cpp
  src/openvic-simulation/politics/Government.cpp
  src/openvic-simulation/politics/Ideology.cpp
  src/openvic-simulation/politics/Issue.cpp
  src/openvic-simulation/politics/NationalFocus.cpp
  src/openvic-simulation/politics/NationalValue.cpp
  src/openvic-simulation/politics/Rebel.cpp
  src/openvic-simulation/politics/Rule.cpp
  src/openvic-simulation/pop/Culture.cpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/Pop.hpp
  src/openvic-simulation/pop/Religion.cpp
  src/openvic-simulation/types/IdentifierRegistry.hpp
  src/openvic-simulation/utility/BMP.cpp
Labels: enhancement

#138 Reworked Units and added IdentifierPointerRegistry
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/interface/LoadBase.hpp
  src/openvic-simulation/military/Deployment.cpp
  src/openvic-simulation/military/Deployment.hpp
  src/openvic-simulation/military/Unit.cpp
  src/openvic-simulation/military/Unit.hpp
  src/openvic-simulation/misc/Modifier.cpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/Pop.hpp
  src/openvic-simulation/types/IdentifierRegistry.hpp
Labels: enhancement

#139 Made Date constexpr so that PROPERTY getters can be constexpr
  src/openvic-simulation/types/Date.cpp
  src/openvic-simulation/types/Date.hpp
  src/openvic-simulation/types/IdentifierRegistry.hpp
  src/openvic-simulation/utility/Getters.hpp
Labels: enhancement

#140 Added StringMapCase and case insensitive expect_dictionary_keys
  src/openvic-simulation/dataloader/NodeTools.cpp
  src/openvic-simulation/dataloader/NodeTools.hpp
  src/openvic-simulation/economy/ProductionType.cpp
  src/openvic-simulation/interface/GFX.cpp
  src/openvic-simulation/interface/GFX.hpp
  src/openvic-simulation/interface/GUI.cpp
  src/openvic-simulation/interface/GUI.hpp
  src/openvic-simulation/interface/LoadBase.hpp
  src/openvic-simulation/map/TerrainType.cpp
  src/openvic-simulation/types/IdentifierRegistry.hpp
  src/openvic-simulation/types/OrderedContainers.hpp
  src/openvic-simulation/utility/Utility.hpp
Labels: enhancement
