Repository OpenVicProject/OpenVic-Simulation, pull requests merged in 2024-11, with the labels that each got.

#223 Add IndexedMap::mapping_type alias for easier interchangeability with ordered_maps
  src/openvic-simulation/types/IndexedMap.hpp
Labels: enhancement

#227 Remove unused (and inaccurate) fixed point members
  src/openvic-simulation/types/fixed_point/FixedPoint.hpp
Labels: bug

#229 artisan_goods_ modifiers have no effect
  src/openvic-simulation/economy/GoodDefinition.cpp
Labels: documentation

#234 Expand Mapmode struct + add default mapmodes
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/map/Mapmode.cpp
  src/openvic-simulation/map/Mapmode.hpp
  src/openvic-simulation/types/HasIdentifier.hpp
Labels: enhancement

#224 Cache pops by type per state and province
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
  src/openvic-simulation/economy/production/ResourceGatheringOperation.hpp
  src/openvic-simulation/map/MapInstance.cpp
  src/openvic-simulation/map/MapInstance.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/map/State.cpp
  src/openvic-simulation/map/State.hpp
Labels: enhancement

#228 ModifierEffectCache & location to fields
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
  src/openvic-simulation/economy/production/ResourceGatheringOperation.hpp
  src/openvic-simulation/map/MapInstance.cpp
  src/openvic-simulation/map/MapInstance.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
Labels: enhancement

#233 Added stores for pop Income solves #225
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/Pop.hpp
Labels: enhancement

#212 Add market placeholder
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/InstanceManager.hpp
  src/openvic-simulation/economy/GoodInstance.cpp
  src/openvic-simulation/economy/GoodInstance.hpp
  src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
  src/openvic-simulation/economy/production/ResourceGatheringOperation.hpp
  src/openvic-simulation/economy/trading/MarketInstance.cpp
  src/openvic-simulation/economy/trading/MarketInstance.hpp
  src/openvic-simulation/economy/trading/MarketSellOrder.cpp
  src/openvic-simulation/economy/trading/MarketSellOrder.hpp
  src/openvic-simulation/economy/trading/SellResult.hpp
  src/openvic-simulation/map/MapInstance.cpp
  src/openvic-simulation/map/MapInstance.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
Labels: enhancement

#237 Fix Backup Path Search Ignoring User-Selected Directory
  src/openvic-simulation/dataloader/Vic2PathSearch.cpp
Labels: bug

#238 Relax BMP data size constraint (allow 0 as unset)
  src/openvic-simulation/utility/BMP.cpp
Labels: bug

#239 Add macro system for vector templates of any size
  src/openvic-simulation/types/Vector.hpp
  src/openvic-simulation/types/VectorN.inc
Labels: enhancement
