Repository OpenVicProject/OpenVic-Simulation, pull requests merged in 2024-12, with the labels that each got.

#240 Add key-value pair iteration to IndexedMap
  src/headless/main.cpp
  src/openvic-simulation/country/CountryDefinition.cpp
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/dataloader/NodeTools.hpp
  src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
  src/openvic-simulation/economy/production/ResourceGatheringOperation.hpp
  src/openvic-simulation/history/CountryHistory.cpp
  src/openvic-simulation/history/CountryHistory.hpp
  src/openvic-simulation/map/MapInstance.cpp
  src/openvic-simulation/map/MapInstance.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/map/State.cpp
  src/openvic-simulation/map/State.hpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/Pop.hpp
  src/openvic-simulation/types/IndexedMap.hpp
  src/openvic-simulation/utility/TslHelper.hpp
Labels: enhancement

#242 Create dependabot.yml for Sim Repo
  .github/workflows/dependabot.yml
Labels: enhancement

#190 Load Gfxobjects
  src/openvic-simulation/dataloader/NodeTools.cpp
  src/openvic-simulation/dataloader/NodeTools.hpp
  src/openvic-simulation/interface/GFXObject.cpp
  src/openvic-simulation/interface/GFXObject.hpp
  src/openvic-simulation/interface/GUI.cpp
  src/openvic-simulation/interface/GUI.hpp
  src/openvic-simulation/map/ProvinceDefinition.cpp
  src/openvic-simulation/map/ProvinceDefinition.hpp
  src/openvic-simulation/types/TextFormat.hpp
Labels: enhancement, help wanted

#244 Add shortcut to BaseButton
  src/openvic-simulation/interface/GUI.cpp
  src/openvic-simulation/interface/GUI.hpp
Labels: enhancement

#245 Treat province town and city positions separately
  src/openvic-simulation/map/MapDefinition.cpp
  src/openvic-simulation/map/MapDefinition.hpp
  src/openvic-simulation/map/ProvinceDefinition.cpp
  src/openvic-simulation/map/ProvinceDefinition.hpp
Labels: bug, enhancement

#243 Fix IndexedMap for bool Value case
  src/openvic-simulation/types/IndexedMap.hpp
  src/openvic-simulation/utility/Utility.hpp
Labels: bug

#246 Fix base_iterator_t friend of itself warning
  src/openvic-simulation/types/IndexedMap.hpp
Labels: bug

#248 Add remaining country budget sliders + has_? functions + has_union_country
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/pop/Culture.hpp
Labels: enhancement

#250 Move dependabot.yml out of workflows folder
  .github/dependabot.yml
Labels: bug

#251 Allow CountryParty ideology to be nullptr
  src/openvic-simulation/country/CountryDefinition.cpp
  src/openvic-simulation/country/CountryDefinition.hpp
  src/openvic-simulation/politics/Ideology.hpp
Labels: bug

#253 Remove BOM from dependabot.yml
  .github/dependabot.yml
Labels: bug

#249 Add flag struct
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/InstanceManager.hpp
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/types/FlagStrings.cpp
  src/openvic-simulation/types/FlagStrings.hpp
Labels: enhancement

#256 Ideology, issue, vote, culture and religion distributions + leader name check
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/map/State.cpp
  src/openvic-simulation/map/State.hpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/Pop.hpp
  src/openvic-simulation/types/IndexedMap.hpp
Labels: enhancement

#258 Add Ideology can_reduce_consciousness variable
  src/openvic-simulation/politics/Ideology.cpp
  src/openvic-simulation/politics/Ideology.hpp
Labels: enhancement

#260 Add PoliticsInstanceManager for tracking enabled ideologies
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/InstanceManager.hpp
  src/openvic-simulation/politics/Ideology.cpp
  src/openvic-simulation/politics/Ideology.hpp
  src/openvic-simulation/politics/PoliticsInstanceManager.cpp
  src/openvic-simulation/politics/PoliticsInstanceManager.hpp
Labels: enhancement

#261 Calculate neighbouring countries and if any colonial provinces are owned
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/types/OrderedContainers.hpp
Labels: enhancement

#262 Calculate more data needed for conditions
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/map/MapInstance.cpp
  src/openvic-simulation/map/MapInstance.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/map/State.cpp
  src/openvic-simulation/map/State.hpp
  src/openvic-simulation/politics/PoliticsInstanceManager.cpp
  src/openvic-simulation/politics/PoliticsInstanceManager.hpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/Pop.hpp
  src/openvic-simulation/types/IndexedMap.hpp
  src/openvic-simulation/types/fixed_point/FixedPoint.hpp
  src/openvic-simulation/types/fixed_point/FixedPointMap.hpp
Labels: bug, enhancement

#263 Rework ConditionalWeight to have starting key/operation variants
  src/openvic-simulation/misc/Decision.cpp
  src/openvic-simulation/misc/Decision.hpp
  src/openvic-simulation/misc/Event.cpp
  src/openvic-simulation/misc/Event.hpp
  src/openvic-simulation/misc/SongChance.cpp
  src/openvic-simulation/misc/SongChance.hpp
  src/openvic-simulation/politics/Ideology.cpp
  src/openvic-simulation/politics/Ideology.hpp
  src/openvic-simulation/politics/Rebel.cpp
  src/openvic-simulation/politics/Rebel.hpp
  src/openvic-simulation/pop/PopType.cpp
  src/openvic-simulation/pop/PopType.hpp
  src/openvic-simulation/research/Invention.cpp
  src/openvic-simulation/research/Invention.hpp
  src/openvic-simulation/research/Technology.cpp
  src/openvic-simulation/research/Technology.hpp
  src/openvic-simulation/scripts/ConditionalWeight.cpp
  src/openvic-simulation/scripts/ConditionalWeight.hpp
  src/openvic-simulation/types/IndexedMap.hpp
Labels: enhancement
