Repository OpenVicProject/OpenVic-Simulation, pull requests merged in 2025-03, with the labels that each got.

#362 Add game rule for economic country
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/map/MapInstance.cpp
  src/openvic-simulation/map/MapInstance.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/misc/GameRulesManager.hpp
Labels: enhancement

#366 Update Github workflow dependencies
  .github/workflows/builds.yml
Labels: enhancement, dependencies

#364 Add support for negative Dates
  src/openvic-simulation/types/Date.cpp
  src/openvic-simulation/types/Date.hpp
  tests/src/types/Date.cpp
Labels: enhancement

#365 Change `Dataloader::apply_to_files` callback capacity and alignment
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/dataloader/Dataloader.hpp
Labels: enhancement

#369 Fix Logger.hpp lacking <version> header
  src/openvic-simulation/utility/Logger.hpp
Labels: bug

#370 Extract `snitch::append` colour print to tests/src/types/Colour.hpp
  tests/src/types/Colour.cpp
  tests/src/types/Colour.hpp
Labels: enhancement

#371 Add default base 10 to `StringUtils::from_chars`
  src/openvic-simulation/utility/StringUtils.hpp
Labels: enhancement

#375 Add early callback skip to type-specific expect functions
  src/openvic-simulation/dataloader/NodeTools.cpp
Labels: bug

#373 Make `name_list_t` type safe
  src/openvic-simulation/dataloader/NodeTools.hpp
Labels: bug

#368 Log valid keys in expect_dictionary_keys
  src/openvic-simulation/dataloader/NodeTools.hpp
  src/openvic-simulation/utility/StringUtils.hpp
Labels: enhancement

#372 Add `fixed_point_t::from_chars` method
  src/openvic-simulation/types/fixed_point/FixedPoint.hpp
  tests/src/types/FixedPoint.cpp
Labels: enhancement

#367 Add NodeTools unit tests
  tests/src/Helper.hpp
  tests/src/dataloader/NodeTools.cpp
Labels: enhancement

#382 Add canal enabling
  src/openvic-simulation/map/MapDefinition.cpp
  src/openvic-simulation/map/MapInstance.cpp
  src/openvic-simulation/map/MapInstance.hpp
  src/openvic-simulation/map/ProvinceDefinition.cpp
  src/openvic-simulation/map/ProvinceDefinition.hpp
Labels: enhancement

#381 Add unemployment count by poptype to province/state/country
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/map/State.cpp
  src/openvic-simulation/map/State.hpp
Labels: enhancement

#378 Add controller country stripes to political mapmode
  src/openvic-simulation/map/Mapmode.cpp
Labels: enhancement

#379 Allow enabling/disabling great and world wars
  src/openvic-simulation/politics/PoliticsInstanceManager.cpp
  src/openvic-simulation/politics/PoliticsInstanceManager.hpp
Labels: enhancement

#380 Add Pop::culture_status_t, has_minorities, better unit allowed cultures check
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/military/UnitType.cpp
  src/openvic-simulation/military/UnitType.hpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/Pop.hpp
Labels: enhancement

#386 Add country and province time properties
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
Labels: enhancement

#385 Use spaces rather than tabs when exact width is needed
  src/openvic-simulation/utility/BMP.hpp
  src/openvic-simulation/utility/Getters.hpp
Labels: enhancement

#387 Calculate civilisation progress + ranking logic cleanup
  src/openvic-simulation/country/CountryInstance.cpp
Labels: enhancement

#388 Add geographical province and country stats
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/map/MapInstance.cpp
  src/openvic-simulation/map/MapInstance.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/map/State.hpp
Labels: enhancement

#390 Fix typo in CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.cpp
Labels: bug

#391 Remove non-numeric province id support
  src/openvic-simulation/map/MapDefinition.cpp
Labels: bug

#392 Add stack string methods to basic_colour_t
  src/openvic-simulation/map/ProvinceDefinition.cpp
  src/openvic-simulation/types/Colour.hpp
Labels: enhancement

#396 Fix missing space for msg error macros
  src/openvic-simulation/utility/ErrorMacros.hpp
Labels: bug

#397 Optimize colour_index_map size in MapDefinition
  src/openvic-simulation/map/MapDefinition.cpp
Labels: enhancement

#398 Change `BuildingInstance::expansion_progress` to fixed_point_t
  src/openvic-simulation/economy/BuildingInstance.cpp
  src/openvic-simulation/economy/BuildingInstance.hpp
  src/openvic-simulation/types/fixed_point/FixedPoint.hpp
Labels: bug, enhancement

#393 Add stack string method to fixed_point_t
  src/openvic-simulation/types/fixed_point/FixedPoint.cpp
  src/openvic-simulation/types/fixed_point/FixedPoint.hpp
  tests/src/types/FixedPoint.cpp
Labels: enhancement

#400 Add merge_group support to builds workflow
  .github/workflows/builds.yml
  .github/workflows/cache_cleanup.yml
Labels: enhancement

#402 Fix CHANGED_FILES in CI
  .github/workflows/builds.yml
Labels: bug

#395 Add land and sea PointMap to MapDefinition
  src/headless/main.cpp
  src/openvic-simulation/map/MapDefinition.cpp
  src/openvic-simulation/map/MapDefinition.hpp
  src/openvic-simulation/map/MapInstance.cpp
  src/openvic-simulation/map/MapInstance.hpp
  src/openvic-simulation/pathfinding/AStarPathing.hpp
  src/openvic-simulation/pathfinding/FringePathing.hpp
  src/openvic-simulation/pathfinding/PointMap.cpp
  src/openvic-simulation/pathfinding/PointMap.hpp
Labels: enhancement

#401 Add constexpr unit tests
  src/openvic-simulation/types/Colour.hpp
  src/openvic-simulation/types/Date.cpp
  src/openvic-simulation/types/Date.hpp
  src/openvic-simulation/types/Vector.hpp
  src/openvic-simulation/types/fixed_point/FixedPoint.cpp
  src/openvic-simulation/types/fixed_point/FixedPoint.hpp
  src/openvic-simulation/utility/StringUtils.hpp
  src/openvic-simulation/utility/Utility.hpp
  tests/src/types/Approx.hpp
  tests/src/types/Colour.cpp
  tests/src/types/Colour.hpp
  tests/src/types/Date.cpp
  tests/src/types/FixedPoint.cpp
  tests/src/types/Numeric.hpp
  tests/src/types/Timespan.cpp
  tests/src/types/Vector.hpp
  tests/src/types/Vector2.cpp
  tests/src/types/Vector3.cpp
  tests/src/types/Vector4.cpp
Labels: enhancement

#404 Fix CHANGED_FILES in CI again
  .github/workflows/builds.yml
Labels: bug

#407 Split war_exhaustion modifier
  src/openvic-simulation/modifier/ModifierEffectCache.cpp
  src/openvic-simulation/modifier/ModifierEffectCache.hpp
  src/openvic-simulation/modifier/ModifierManager.cpp
Labels: enhancement

#406 Move LUT fixed point generator scripts to misc/scripts
  misc/scripts/exp_lut_generator.py
  misc/scripts/sin_lut_generator.py
  src/openvic-simulation/types/fixed_point/FixedPoint.hpp
  src/openvic-simulation/types/fixed_point/FixedPointLUT_2_16_EXP_2001.hpp
  src/openvic-simulation/types/fixed_point/FixedPointLUT_2_16_EXP_e.hpp
  src/openvic-simulation/types/fixed_point/FixedPointLUT_sin.hpp
  src/openvic-simulation/types/fixed_point/lut_generator/exp_lut_generator.py
  src/openvic-simulation/types/fixed_point/lut_generator/sin_lut_generator.py
Labels: enhancement

#405 Add Builds CI status badge to README
  README.md
Labels: enhancement

#403 Optimize vector construction
  src/openvic-simulation/console/ConsoleInstance.cpp
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
  src/openvic-simulation/economy/trading/GoodMarket.cpp
  src/openvic-simulation/economy/trading/GoodMarket.hpp
  src/openvic-simulation/economy/trading/MarketInstance.cpp
  src/openvic-simulation/economy/trading/MarketInstance.hpp
  src/openvic-simulation/history/DiplomaticHistory.cpp
  src/openvic-simulation/history/DiplomaticHistory.hpp
  src/openvic-simulation/interface/GFXObject.cpp
  src/openvic-simulation/interface/GFXObject.hpp
  src/openvic-simulation/map/MapDefinition.cpp
  src/openvic-simulation/map/MapDefinition.hpp
  src/openvic-simulation/map/State.cpp
  src/openvic-simulation/map/State.hpp
  src/openvic-simulation/military/Deployment.cpp
  src/openvic-simulation/military/Deployment.hpp
  src/openvic-simulation/military/Leader.hpp
  src/openvic-simulation/misc/Event.cpp
  src/openvic-simulation/misc/Event.hpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/utility/Utility.hpp
  tests/src/utility/DualAdjacent.cpp
Labels: enhancement
