Repository OpenVicProject/OpenVic-Simulation, pull requests merged in 2025-07, with the labels that each got.

#473 Fix admin efficiency calculation
  src/openvic-simulation/country/CountryInstance.cpp
Labels: bug, topic:economy

#476 Streamline commit_info.gen generator in SConstruct
  SConstruct
Labels: enhancement, topic:buildsystem

#480 Add this check for `CountryInstance::can_army_units_enter`
  src/openvic-simulation/country/CountryInstance.cpp
Labels: bug, topic:core

#482 Support == for HasIndex using type tagging
  src/openvic-simulation/country/CountryDefinition.hpp
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/economy/GoodDefinition.hpp
  src/openvic-simulation/economy/production/ArtisanalProducer.cpp
  src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
  src/openvic-simulation/history/Bookmark.hpp
  src/openvic-simulation/history/DiplomaticHistory.cpp
  src/openvic-simulation/map/Mapmode.cpp
  src/openvic-simulation/map/Mapmode.hpp
  src/openvic-simulation/map/ProvinceDefinition.cpp
  src/openvic-simulation/map/ProvinceDefinition.hpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/politics/Issue.hpp
  src/openvic-simulation/politics/Rule.hpp
  src/openvic-simulation/pop/PopType.cpp
  src/openvic-simulation/pop/PopType.hpp
  src/openvic-simulation/research/Technology.hpp
  src/openvic-simulation/types/HasIdentifier.hpp
Labels: enhancement, topic:core

#483 Fix log scope duplicated symbol error with clang
  src/openvic-simulation/utility/Logger.cpp
  src/openvic-simulation/utility/Logger.hpp
Labels: bug, platform:macos, topic:core

#484 Added get_strata_taxable_income to CountryInstance
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
Labels: enhancement, topic:economy

#485 Government salaries & social welfare / Pop::size_denominator
  src/openvic-simulation/country/CountryInstance.cpp
Labels: bug, topic:economy

#477 Add COPYRIGHT file
  COPYRIGHT
  SConstruct
Labels: documentation, enhancement, topic:buildsystem, meta, topic:core

#481 Add AUTHORS.md
  AUTHORS.md
  SConstruct
Labels: documentation, enhancement, topic:buildsystem, meta, topic:core

#487 Round fixed_point_t to int away from zero
  src/openvic-simulation/types/fixed_point/FixedPoint.hpp
  tests/src/types/FixedPoint.cpp
Labels: enhancement, topic:core

#474 Add cow_vector
  src/openvic-simulation/types/BasicIterator.hpp
  src/openvic-simulation/types/CowPtr.hpp
  src/openvic-simulation/types/CowVector.hpp
  src/openvic-simulation/types/Signal.hpp
  src/openvic-simulation/utility/Deque.hpp
  src/openvic-simulation/utility/Utility.hpp
Labels: enhancement, topic:core

#384 Apply clang-tidy fixes
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/dataloader/NodeTools.hpp
  src/openvic-simulation/defines/AIDefines.cpp
  src/openvic-simulation/defines/AIDefines.hpp
  src/openvic-simulation/defines/CountryDefines.cpp
  src/openvic-simulation/defines/CountryDefines.hpp
  src/openvic-simulation/defines/Define.cpp
  src/openvic-simulation/defines/DiplomacyDefines.cpp
  src/openvic-simulation/defines/DiplomacyDefines.hpp
  src/openvic-simulation/defines/EconomyDefines.cpp
  src/openvic-simulation/defines/EconomyDefines.hpp
  src/openvic-simulation/defines/GraphicsDefines.cpp
  src/openvic-simulation/defines/GraphicsDefines.hpp
  src/openvic-simulation/defines/MilitaryDefines.cpp
  src/openvic-simulation/defines/MilitaryDefines.hpp
  src/openvic-simulation/defines/PopsDefines.cpp
  src/openvic-simulation/defines/PopsDefines.hpp
  src/openvic-simulation/economy/BuildingInstance.cpp
  src/openvic-simulation/economy/BuildingInstance.hpp
  src/openvic-simulation/economy/production/ArtisanalProducerFactoryPattern.cpp
  src/openvic-simulation/economy/production/ArtisanalProducerFactoryPattern.hpp
  src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
  src/openvic-simulation/economy/production/ResourceGatheringOperation.hpp
  src/openvic-simulation/economy/trading/GoodMarket.cpp
  src/openvic-simulation/economy/trading/GoodMarket.hpp
  src/openvic-simulation/history/DiplomaticHistory.cpp
  src/openvic-simulation/interface/GFXObject.cpp
  src/openvic-simulation/interface/GFXObject.hpp
  src/openvic-simulation/interface/GFXSprite.cpp
  src/openvic-simulation/interface/GFXSprite.hpp
  src/openvic-simulation/interface/GUI.cpp
  src/openvic-simulation/interface/GUI.hpp
  src/openvic-simulation/map/MapDefinition.cpp
  src/openvic-simulation/map/MapDefinition.hpp
  src/openvic-simulation/map/ProvinceDefinition.cpp
  src/openvic-simulation/map/ProvinceDefinition.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/misc/GameRulesManager.hpp
  src/openvic-simulation/modifier/StaticModifierCache.cpp
  src/openvic-simulation/modifier/StaticModifierCache.hpp
  src/openvic-simulation/scripts/ConditionalWeight.cpp
  src/openvic-simulation/scripts/ConditionalWeight.hpp
  src/openvic-simulation/types/IdentifierRegistry.hpp
  src/openvic-simulation/utility/NumberUtils.hpp
  tests/benchmarks/src/dataloading/Dataloading.cpp
Labels: bug, enhancement, topic:codestyle

#488 Rename stockpile sliders land > army & naval > navy
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/defines/EconomyDefines.cpp
  src/openvic-simulation/defines/EconomyDefines.hpp
  src/openvic-simulation/misc/GameAction.cpp
  src/openvic-simulation/misc/GameAction.hpp
Labels: topic:economy

#489 Add foonathan/memory license and copyright info
  COPYRIGHT
Labels: bug, documentation, topic:buildsystem, meta

#490 Fix static modifier names
  src/openvic-simulation/modifier/StaticModifierCache.hpp
Labels: bug, topic:dataloader

#491 Improve invalid key message in history
  src/openvic-simulation/history/CountryHistory.cpp
  src/openvic-simulation/history/HistoryMap.hpp
  src/openvic-simulation/history/ProvinceHistory.cpp
Labels: enhancement, topic:dataloader

#492 Ignore foonathan/memory gen files
  .gitmodules
Labels: submodules, meta

#496 Use index from HasIndex in IndexedMap
  src/openvic-simulation/types/HasIdentifier.hpp
  src/openvic-simulation/types/HasIndex.hpp
  src/openvic-simulation/types/IndexedMap.hpp
Labels: enhancement, performance, topic:core

#497 Subtract expenses from cash_stockpile in country_tick_before_map
  src/openvic-simulation/country/CountryInstance.cpp
Labels: bug, topic:economy

#501 Fix CowVector.hpp and Pop.cpp not compiling under apple clang 17
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/types/CowVector.hpp
Labels: bug, regression, platform:macos, topic:core

#502 Add HasIndex to ideology
  src/openvic-simulation/politics/Ideology.cpp
  src/openvic-simulation/politics/Ideology.hpp
Labels: enhancement, performance

#505 Added get_tariff_efficiency to CountryInstance
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
Labels: enhancement, topic:economy

#506 Properties for admin eff tooltip
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/defines/CountryDefines.hpp
Labels: enhancement

#504 Clearly distinguish between 0- & 1-based indexing
  src/openvic-simulation/console/ConsoleInstance.cpp
  src/openvic-simulation/history/ProvinceHistory.cpp
  src/openvic-simulation/map/MapDefinition.cpp
  src/openvic-simulation/map/MapDefinition.hpp
  src/openvic-simulation/map/MapInstance.cpp
  src/openvic-simulation/map/Mapmode.cpp
  src/openvic-simulation/map/ProvinceDefinition.cpp
  src/openvic-simulation/map/ProvinceDefinition.hpp
  src/openvic-simulation/misc/GameAction.cpp
  src/openvic-simulation/pathfinding/AStarPathing.cpp
  src/openvic-simulation/types/HasIndex.hpp
  src/openvic-simulation/types/IdentifierRegistry.hpp
Labels: bug, topic:core

#510 Add sigslot to COPYRIGHT
  COPYRIGHT
Labels: bug, documentation, meta, topic:core

#511 Expose vector properties via span
  src/headless/main.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/map/State.hpp
  src/openvic-simulation/military/UnitInstanceGroup.hpp
  src/openvic-simulation/utility/Getters.hpp
Labels: enhancement, topic:codestyle

#512 Refactor index_1_based to province_number
  src/openvic-simulation/console/ConsoleInstance.cpp
  src/openvic-simulation/console/ConsoleInstance.hpp
  src/openvic-simulation/map/MapDefinition.cpp
  src/openvic-simulation/map/MapDefinition.hpp
  src/openvic-simulation/map/MapInstance.cpp
  src/openvic-simulation/map/MapInstance.hpp
  src/openvic-simulation/map/Mapmode.cpp
  src/openvic-simulation/map/ProvinceDefinition.cpp
  src/openvic-simulation/map/ProvinceDefinition.hpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/misc/GameAction.cpp
  src/openvic-simulation/pathfinding/AStarPathing.cpp
  src/openvic-simulation/types/IdentifierRegistry.hpp
Labels: enhancement, topic:codestyle
