Repository OpenVicProject/OpenVic-Simulation, pull requests merged in 2025-08, with the labels that each got.

#515 Return fixed_point_t& for *= and such
  src/openvic-simulation/types/fixed_point/FixedPoint.hpp
Labels: bug, topic:core

#516 Replace IndexedMap
  src/openvic-simulation/country/CountryDefinition.cpp
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/country/CountryParty.hpp
  src/openvic-simulation/country/SharedCountryValues.cpp
  src/openvic-simulation/country/SharedCountryValues.hpp
  src/openvic-simulation/dataloader/NodeTools.hpp
  src/openvic-simulation/economy/BuildingType.cpp
  src/openvic-simulation/economy/GoodDefinition.cpp
  src/openvic-simulation/economy/production/ArtisanalProducer.cpp
  src/openvic-simulation/economy/production/ArtisanalProducer.hpp
  src/openvic-simulation/economy/production/ProductionType.cpp
  src/openvic-simulation/economy/production/ProductionType.hpp
  src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
  src/openvic-simulation/economy/production/ResourceGatheringOperation.hpp
  src/openvic-simulation/economy/trading/GoodMarket.cpp
  src/openvic-simulation/economy/trading/GoodMarket.hpp
  src/openvic-simulation/history/CountryHistory.hpp
  src/openvic-simulation/history/ProvinceHistory.cpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/map/State.cpp
  src/openvic-simulation/map/State.hpp
  src/openvic-simulation/map/TerrainType.cpp
  src/openvic-simulation/military/UnitBranchedGetterMacro.hpp
  src/openvic-simulation/military/UnitType.cpp
  src/openvic-simulation/modifier/ModifierEffectCache.hpp
  src/openvic-simulation/politics/PoliticsInstanceManager.cpp
  src/openvic-simulation/politics/PoliticsInstanceManager.hpp
  src/openvic-simulation/politics/Rebel.cpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/Pop.hpp
  src/openvic-simulation/pop/PopManager.cpp
  src/openvic-simulation/pop/PopType.hpp
  src/openvic-simulation/pop/PopValuesFromProvince.cpp
  src/openvic-simulation/pop/PopValuesFromProvince.hpp
  src/openvic-simulation/research/Technology.cpp
  src/openvic-simulation/types/HasIndex.hpp
  src/openvic-simulation/types/IndexedFlatMap.hpp
  src/openvic-simulation/types/IndexedFlatMapMacro.hpp
  src/openvic-simulation/types/IndexedMap.hpp
  src/openvic-simulation/utility/ThreadPool.cpp
Labels: enhancement, topic:core

#470 Load all mod descriptors and check dependencies
  src/headless/main.cpp
  src/openvic-simulation/GameManager.cpp
  src/openvic-simulation/GameManager.hpp
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/dataloader/Dataloader.hpp
  src/openvic-simulation/dataloader/ModManager.cpp
  src/openvic-simulation/dataloader/ModManager.hpp
  tests/benchmarks/src/dataloading/Dataloading.cpp
Labels: enhancement, topic:core

#519 Pops aggregate
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/map/MapInstance.cpp
  src/openvic-simulation/map/MapInstance.hpp
  src/openvic-simulation/map/Mapmode.cpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/map/State.cpp
  src/openvic-simulation/map/State.hpp
  src/openvic-simulation/pop/PopsAggregate.cpp
  src/openvic-simulation/pop/PopsAggregate.hpp
Labels: enhancement, topic:core

#521 Reduce dependabot label automation run attempts
  .github/workflows/dependabot-labels.yml
Labels: enhancement, dependencies, meta

#522 Use IWYU pragma: keep
  src/openvic-simulation/country/CountryParty.hpp
  src/openvic-simulation/map/State.hpp
  src/openvic-simulation/military/UnitBranchedGetterMacro.hpp
  src/openvic-simulation/modifier/ModifierEffectCache.hpp
  src/openvic-simulation/politics/PoliticsInstanceManager.hpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/PopValuesFromProvince.cpp
  src/openvic-simulation/types/Colour.cpp
  src/openvic-simulation/types/IndexedFlatMapMacro.hpp
  src/openvic-simulation/types/Vector.cpp
  src/openvic-simulation/types/fixed_point/FixedPointMap.hpp
  src/openvic-simulation/utility/ErrorMacros.hpp
Labels: enhancement, topic:codestyle

#524 Use mutable it.value() for ordered_map += and such
  src/openvic-simulation/types/OrderedContainersMath.hpp
Labels: bug, topic:core

#523 Automatic dependency tracking
  src/headless/main.cpp
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/country/SharedCountryValues.cpp
  src/openvic-simulation/country/SharedCountryValues.hpp
  src/openvic-simulation/economy/production/Employee.cpp
  src/openvic-simulation/economy/production/Employee.hpp
  src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
  src/openvic-simulation/map/State.cpp
  src/openvic-simulation/map/State.hpp
  src/openvic-simulation/misc/GameAction.cpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/PopType.hpp
  src/openvic-simulation/pop/PopValuesFromProvince.cpp
  src/openvic-simulation/pop/PopsAggregate.cpp
  src/openvic-simulation/pop/PopsAggregate.hpp
  src/openvic-simulation/types/Signal.hpp
  src/openvic-simulation/types/SliderValue.hpp
  src/openvic-simulation/utility/MathConcepts.hpp
  src/openvic-simulation/utility/reactive/DependencyTracker.hpp
  src/openvic-simulation/utility/reactive/DerivedState.hpp
  src/openvic-simulation/utility/reactive/MutableState.hpp
Labels: enhancement, topic:core

#532 Support initialisation in STATE_PROPERTY
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/utility/reactive/MutableState.hpp
Labels: enhancement, topic:codestyle

#533 Add standard opinion identifier getter
  src/openvic-simulation/diplomacy/CountryRelation.hpp
Labels: enhancement, topic:diplomacy

#530 Add sphere_owner property to CountryInstance
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
Labels: enhancement, topic:diplomacy

#535 Correct connection methods
  src/openvic-simulation/utility/reactive/DerivedState.hpp
  src/openvic-simulation/utility/reactive/MutableState.hpp
Labels: bug, topic:core

#536 Remove CountryInstance methods without implementation
  src/openvic-simulation/country/CountryInstance.hpp
Labels: bug, topic:core

#540 Specify type on forward
  src/openvic-simulation/utility/reactive/MutableState.hpp
Labels: bug, topic:core

#541 Unit tests for MutableState & DerivedState
  tests/src/types/Signal.cpp
  tests/src/utility/reactive/DerivedState.cpp
  tests/src/utility/reactive/MutableState.cpp
Labels: enhancement

#542 Add owned_province in set_owner
  src/openvic-simulation/map/ProvinceInstance.cpp
Labels: bug, topic:core

#543 Lock is_dirty_lock shorter
  src/openvic-simulation/utility/reactive/DependencyTracker.hpp
  tests/src/utility/reactive/DerivedState.cpp
Labels: bug, topic:core
