Repository OpenVicProject/OpenVic-Simulation, pull requests merged in 2025-01, with the labels that each got.

#264 Ensure registries get locked even if they're empty
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/map/MapDefinition.cpp
  src/openvic-simulation/map/MapInstance.cpp
Labels: bug

#265 Add country military stats, load assigned leaders, fix 1861 core errors
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/defines/Define.cpp
  src/openvic-simulation/history/CountryHistory.cpp
  src/openvic-simulation/history/CountryHistory.hpp
  src/openvic-simulation/map/MapInstance.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/military/Deployment.cpp
  src/openvic-simulation/military/Deployment.hpp
  src/openvic-simulation/military/Leader.cpp
  src/openvic-simulation/military/Leader.hpp
  src/openvic-simulation/military/LeaderTrait.cpp
  src/openvic-simulation/military/LeaderTrait.hpp
  src/openvic-simulation/military/UnitInstanceGroup.cpp
  src/openvic-simulation/military/UnitInstanceGroup.hpp
  src/openvic-simulation/modifier/Modifier.hpp
  src/openvic-simulation/types/FlagStrings.cpp
  src/openvic-simulation/types/FlagStrings.hpp
  src/openvic-simulation/types/IdentifierRegistry.hpp
Labels: bug, enhancement

#266 Find and use cultural leader pictures, fix modifier effect formats, add branch(ed) names
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/military/Deployment.cpp
  src/openvic-simulation/military/Leader.cpp
  src/openvic-simulation/military/Leader.hpp
  src/openvic-simulation/military/UnitInstance.hpp
  src/openvic-simulation/military/UnitInstanceGroup.cpp
  src/openvic-simulation/military/UnitInstanceGroup.hpp
  src/openvic-simulation/military/UnitType.hpp
  src/openvic-simulation/modifier/ModifierManager.cpp
  src/openvic-simulation/modifier/ModifierManager.hpp
  src/openvic-simulation/modifier/StaticModifierCache.cpp
  src/openvic-simulation/politics/Issue.cpp
  src/openvic-simulation/pop/Culture.cpp
  src/openvic-simulation/pop/Culture.hpp
Labels: bug, enhancement

#268 Add ModifierSum::for_each_contributing_modifier
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/defines/CountryDefines.cpp
  src/openvic-simulation/defines/CountryDefines.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/modifier/ModifierManager.cpp
  src/openvic-simulation/modifier/ModifierSum.cpp
  src/openvic-simulation/modifier/ModifierSum.hpp
Labels: bug, enhancement

#270 Add optional initializer support to PROPERTY macros
  src/openvic-simulation/utility/Getters.hpp
Labels: enhancement

#269 Use combined ModifierEffects for farm/mine_rgo_eff rather than splitting into output & throughput
  src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
  src/openvic-simulation/modifier/ModifierEffectCache.cpp
  src/openvic-simulation/modifier/ModifierEffectCache.hpp
  src/openvic-simulation/modifier/ModifierManager.cpp
Labels: enhancement

#274 Add TerrainType movement_cost, IdentifierRegistry back(), allow no trigger Crimes
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/economy/production/ProductionType.cpp
  src/openvic-simulation/economy/production/ProductionType.hpp
  src/openvic-simulation/interface/UI.cpp
  src/openvic-simulation/map/Crime.cpp
  src/openvic-simulation/map/MapDefinition.cpp
  src/openvic-simulation/map/TerrainType.cpp
  src/openvic-simulation/map/TerrainType.hpp
  src/openvic-simulation/military/Deployment.cpp
  src/openvic-simulation/military/UnitType.cpp
  src/openvic-simulation/modifier/Modifier.cpp
  src/openvic-simulation/modifier/Modifier.hpp
  src/openvic-simulation/modifier/ModifierEffectCache.cpp
  src/openvic-simulation/modifier/ModifierEffectCache.hpp
  src/openvic-simulation/modifier/ModifierManager.cpp
  src/openvic-simulation/pop/Culture.cpp
  src/openvic-simulation/pop/PopType.cpp
  src/openvic-simulation/research/Technology.cpp
  src/openvic-simulation/research/Technology.hpp
  src/openvic-simulation/types/IdentifierRegistry.hpp
  src/openvic-simulation/types/fixed_point/FixedPoint.hpp
  src/openvic-simulation/utility/Getters.hpp
Labels: bug, enhancement

#273 Rework ModifierSum calculations
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
  src/openvic-simulation/map/MapInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/modifier/ModifierEffect.hpp
  src/openvic-simulation/modifier/ModifierSum.cpp
  src/openvic-simulation/modifier/ModifierSum.hpp
  src/openvic-simulation/modifier/ModifierValue.cpp
  src/openvic-simulation/modifier/ModifierValue.hpp
Labels: enhancement

#230 Add Artisanal production + buying from market
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/InstanceManager.hpp
  src/openvic-simulation/economy/GoodInstance.cpp
  src/openvic-simulation/economy/GoodInstance.hpp
  src/openvic-simulation/economy/production/ArtisanalProducer.cpp
  src/openvic-simulation/economy/production/ArtisanalProducer.hpp
  src/openvic-simulation/economy/production/ArtisanalProducerFactoryPattern.cpp
  src/openvic-simulation/economy/production/ArtisanalProducerFactoryPattern.hpp
  src/openvic-simulation/economy/trading/BuyResult.hpp
  src/openvic-simulation/economy/trading/BuyUpToOrder.cpp
  src/openvic-simulation/economy/trading/BuyUpToOrder.hpp
  src/openvic-simulation/economy/trading/MarketInstance.cpp
  src/openvic-simulation/economy/trading/MarketInstance.hpp
  src/openvic-simulation/economy/trading/SellResult.hpp
  src/openvic-simulation/map/MapInstance.cpp
  src/openvic-simulation/map/MapInstance.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/misc/GameRulesManager.hpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/Pop.hpp
  src/openvic-simulation/types/fixed_point/FixedPoint.hpp
  src/openvic-simulation/utility/CompilerFeatureTesting.hpp
Labels: enhancement

#276 Add PROPERTY_PTR with non-const pointer getter + cleanup constructors
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/InstanceManager.hpp
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/map/MapInstance.cpp
  src/openvic-simulation/map/MapInstance.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/map/State.cpp
  src/openvic-simulation/map/State.hpp
  src/openvic-simulation/military/Leader.hpp
  src/openvic-simulation/military/UnitInstance.hpp
  src/openvic-simulation/military/UnitInstanceGroup.cpp
  src/openvic-simulation/military/UnitInstanceGroup.hpp
  src/openvic-simulation/utility/Getters.hpp
Labels: enhancement

#281 Add country research and leadership point gain + tech research
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/dataloader/NodeTools.hpp
  src/openvic-simulation/defines/MilitaryDefines.hpp
  src/openvic-simulation/research/Technology.cpp
  src/openvic-simulation/research/Technology.hpp
  src/openvic-simulation/types/Date.hpp
  src/openvic-simulation/types/IdentifierRegistry.hpp
  src/openvic-simulation/types/fixed_point/FixedPoint.hpp
Labels: enhancement

#282 Check amount > 0 before placing order/adding pop income
  src/openvic-simulation/economy/production/ArtisanalProducer.cpp
  src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
Labels: bug

#284 Remove fixed point destructor
  src/openvic-simulation/types/fixed_point/FixedPoint.hpp
Labels: enhancement

#286 Make Logger thread safe
  src/openvic-simulation/utility/Logger.hpp
Labels: bug

#285 First steps of unit stats and behaviour (parts needed for military menu)
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/military/UnitInstance.cpp
  src/openvic-simulation/military/UnitInstance.hpp
  src/openvic-simulation/military/UnitInstanceGroup.cpp
  src/openvic-simulation/military/UnitInstanceGroup.hpp
  src/openvic-simulation/modifier/ModifierManager.cpp
Labels: enhancement
