Repository OpenVicProject/OpenVic-Simulation, pull requests merged in 2025-02, with the labels that each got.

#287 Fix Windows/macOS insensitive filesystem presumption
  src/openvic-simulation/dataloader/Dataloader.cpp
Labels: bug

#289 Fix glib not linking libtbb
  .github/workflows/builds.yml
  deps/SCsub
Labels: bug

#288 Add trade data, good enabling, price history
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/InstanceManager.hpp
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/economy/GoodDefinition.cpp
  src/openvic-simulation/economy/GoodDefinition.hpp
  src/openvic-simulation/economy/GoodInstance.cpp
  src/openvic-simulation/economy/GoodInstance.hpp
  src/openvic-simulation/economy/trading/MarketInstance.cpp
  src/openvic-simulation/economy/trading/MarketInstance.hpp
  src/openvic-simulation/types/ValueHistory.hpp
Labels: enhancement

#290 Add TechnologyFolder index variable
  src/openvic-simulation/research/Technology.cpp
  src/openvic-simulation/research/Technology.hpp
Labels: enhancement

#275 Dynamic pricing
  src/openvic-simulation/economy/GoodInstance.cpp
  src/openvic-simulation/economy/GoodInstance.hpp
  src/openvic-simulation/economy/production/ArtisanalProducer.cpp
  src/openvic-simulation/economy/production/ArtisanalProducerFactoryPattern.hpp
  src/openvic-simulation/economy/production/FactoryProducer.cpp
  src/openvic-simulation/economy/trading/BuyUpToOrder.hpp
  src/openvic-simulation/interface/GFXObject.hpp
  src/openvic-simulation/map/MapDefinition.cpp
  src/openvic-simulation/misc/GameRulesManager.hpp
  src/openvic-simulation/pop/Pop.hpp
Labels: enhancement

#292 Add simulation dev console
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/InstanceManager.hpp
  src/openvic-simulation/console/ConsoleInstance.cpp
  src/openvic-simulation/console/ConsoleInstance.hpp
  src/openvic-simulation/types/Colour.hpp
Labels: enhancement

#298 Replace MSVC STL deque to support 512 block size
  src/openvic-simulation/types/IdentifierRegistry.hpp
  src/openvic-simulation/types/OrderedContainers.hpp
  src/openvic-simulation/utility/Deque.hpp
Labels: enhancement

#299 Add proper clicksound Button support
  src/openvic-simulation/DefinitionManager.cpp
  src/openvic-simulation/DefinitionManager.hpp
  src/openvic-simulation/GameManager.hpp
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/interface/GUI.cpp
  src/openvic-simulation/interface/GUI.hpp
  src/openvic-simulation/interface/UI.cpp
  src/openvic-simulation/interface/UI.hpp
  src/openvic-simulation/misc/SoundEffect.cpp
  src/openvic-simulation/misc/SoundEffect.hpp
  src/openvic-simulation/utility/Getters.hpp
Labels: enhancement

#293 Add more unit tests
  SConstruct
  src/openvic-simulation/console/ConsoleInstance.cpp
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/dataloader/NodeTools.cpp
  src/openvic-simulation/history/HistoryMap.hpp
  src/openvic-simulation/map/MapDefinition.cpp
  src/openvic-simulation/types/Colour.cpp
  src/openvic-simulation/types/Colour.hpp
  src/openvic-simulation/types/Date.cpp
  src/openvic-simulation/types/Date.hpp
  src/openvic-simulation/types/Vector.cpp
  src/openvic-simulation/types/Vector.hpp
  src/openvic-simulation/types/VectorN.inc
  src/openvic-simulation/types/fixed_point/FixedPoint.hpp
  src/openvic-simulation/utility/Utility.hpp
  tests/SCsub
  tests/src/Helper.hpp
  tests/src/pathfinding/PointMap.cpp
  tests/src/types/Approx.hpp
  tests/src/types/Colour.cpp
  tests/src/types/Date.cpp
  tests/src/types/FixedPoint.cpp
  tests/src/types/Numeric.hpp
  tests/src/types/Timespan.cpp
  tests/src/types/Vector.hpp
  tests/src/types/Vector2.cpp
  tests/src/types/Vector3.cpp
  tests/src/types/Vector4.cpp
Labels: enhancement

#300 Fix invalid clicksound pointer
  src/openvic-simulation/interface/GUI.hpp
Labels: bug

#301 Fix std::accumulate int conversion warning
  src/openvic-simulation/types/Date.hpp
Labels: bug

#304 Store vectors of personality and background leader traits to choose from when generating leaders
  src/openvic-simulation/dataloader/NodeTools.hpp
  src/openvic-simulation/map/Region.cpp
  src/openvic-simulation/map/Region.hpp
  src/openvic-simulation/military/LeaderTrait.cpp
  src/openvic-simulation/military/LeaderTrait.hpp
  src/openvic-simulation/types/IdentifierRegistry.hpp
Labels: enhancement

#305 Fix research completion data calculation + tech supply_limit ModifierEffect format
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/modifier/ModifierManager.cpp
Labels: bug

#306 Add country good data getters and is_trading_good for trade menu
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/economy/GoodDefinition.cpp
  src/openvic-simulation/economy/GoodInstance.hpp
Labels: enhancement

#307 Add country and province instance indices + country_definition_to_instance_map
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/map/MapInstance.cpp
  src/openvic-simulation/map/Mapmode.cpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
Labels: enhancement

#297 Pop needs & spending
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/economy/GoodInstance.cpp
  src/openvic-simulation/economy/GoodInstance.hpp
  src/openvic-simulation/economy/production/ArtisanalProducer.cpp
  src/openvic-simulation/economy/production/ArtisanalProducer.hpp
  src/openvic-simulation/economy/production/ArtisanalProducerFactoryPattern.cpp
  src/openvic-simulation/economy/production/ArtisanalProducerFactoryPattern.hpp
  src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
  src/openvic-simulation/economy/production/ResourceGatheringOperation.hpp
  src/openvic-simulation/map/MapInstance.cpp
  src/openvic-simulation/map/MapInstance.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/Pop.hpp
  src/openvic-simulation/pop/PopValuesFromProvince.cpp
  src/openvic-simulation/pop/PopValuesFromProvince.hpp
Labels: enhancement

#313 CountryInstance fixes
  src/openvic-simulation/country/CountryInstance.hpp
Labels: bug

#302 Rework military structs to have branch-agnostic bases and unique ids
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/military/Deployment.cpp
  src/openvic-simulation/military/Leader.cpp
  src/openvic-simulation/military/Leader.hpp
  src/openvic-simulation/military/UnitInstance.cpp
  src/openvic-simulation/military/UnitInstance.hpp
  src/openvic-simulation/military/UnitInstanceGroup.cpp
  src/openvic-simulation/military/UnitInstanceGroup.hpp
Labels: enhancement

#310 Record production & consumption
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/economy/GoodInstance.cpp
  src/openvic-simulation/economy/production/ArtisanalProducer.cpp
  src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
Labels: enhancement

#315 Record country demand
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/economy/production/ArtisanalProducer.cpp
  src/openvic-simulation/misc/GameRulesManager.hpp
  src/openvic-simulation/pop/Pop.cpp
Labels: enhancement

#317 Improve calculation accuracy by avoiding shifting via mul_div
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/economy/production/ArtisanalProducer.cpp
  src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
  src/openvic-simulation/economy/trading/GoodMarket.cpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/types/fixed_point/FixedPoint.hpp
  tests/src/types/FixedPoint.cpp
Labels: bug

#319 Remove selected province, add player country+selected province mapmode args
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/InstanceManager.hpp
  src/openvic-simulation/map/MapInstance.cpp
  src/openvic-simulation/map/MapInstance.hpp
  src/openvic-simulation/map/Mapmode.cpp
  src/openvic-simulation/map/Mapmode.hpp
Labels: enhancement

#318 Store vectors of Issues/Reforms under each IssueGroup/ReformGroup
  src/openvic-simulation/country/CountryDefinition.cpp
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/politics/Issue.cpp
  src/openvic-simulation/politics/Issue.hpp
  src/openvic-simulation/pop/Pop.cpp
Labels: enhancement

#316 Fix pop need modifiers
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/economy/GoodInstance.cpp
  src/openvic-simulation/economy/GoodInstance.hpp
  src/openvic-simulation/economy/production/ArtisanalProducer.cpp
  src/openvic-simulation/economy/production/ArtisanalProducer.hpp
  src/openvic-simulation/economy/trading/GoodMarket.cpp
  src/openvic-simulation/economy/trading/GoodMarket.hpp
  src/openvic-simulation/economy/trading/MarketInstance.cpp
  src/openvic-simulation/economy/trading/MarketInstance.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/Pop.hpp
  src/openvic-simulation/pop/PopValuesFromProvince.cpp
  src/openvic-simulation/pop/PopValuesFromProvince.hpp
  src/openvic-simulation/types/Vector.hpp
Labels: bug

#321 Resolved comments on fix_need_modifiers PR
  src/openvic-simulation/economy/GoodInstance.hpp
  src/openvic-simulation/economy/trading/GoodMarket.hpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/Pop.hpp
Labels: enhancement

#322 Fix RGO hiring
  src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
  src/openvic-simulation/pop/Pop.cpp
Labels: bug

#325 Add parallel_for_each range
  src/openvic-simulation/economy/trading/GoodMarket.cpp
  src/openvic-simulation/economy/trading/MarketInstance.cpp
  src/openvic-simulation/map/MapInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/utility/CompilerFeatureTesting.hpp
Labels: bug, enhancement

#330 Add std::atomic<fixed_point_t> specialization
  src/openvic-simulation/types/fixed_point/Atomic.hpp
  src/openvic-simulation/utility/Utility.hpp
Labels: enhancement

#328 Thread safe pop tick and callbacks
  src/openvic-simulation/economy/production/ArtisanalProducer.cpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/Pop.hpp
Labels: bug

#332 Fix MSVC ambiguous fixed_point_t atomic conversion errors
  src/openvic-simulation/types/fixed_point/Atomic.hpp
Labels: bug

#331 Add unit tests for atomic fixed_point_t
  tests/src/types/AtomicFixedPoint.cpp
Labels: enhancement

#336 Improve thread safety comment for artisan
  src/openvic-simulation/economy/production/ArtisanalProducer.hpp
Labels: documentation

#335 Fix unknown forceinline attribute warnings
  src/openvic-simulation/utility/Utility.hpp
Labels: bug

#333 Use movable atomic to simplify move constructor
  src/openvic-simulation/economy/production/ArtisanalProducer.cpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/Pop.hpp
  src/openvic-simulation/types/fixed_point/Atomic.hpp
Labels: enhancement

#338 Fix MSVC inline used more than once warnings
  src/openvic-simulation/utility/Utility.hpp
Labels: bug

#334 Make SliderValue use fixed_point_t + calculate slider range modifiers
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/defines/EconomyDefines.cpp
  src/openvic-simulation/defines/EconomyDefines.hpp
  src/openvic-simulation/types/SliderValue.hpp
  src/openvic-simulation/types/fixed_point/Atomic.hpp
  src/openvic-simulation/types/fixed_point/FixedPoint.hpp
Labels: enhancement

#303 Implement country diplomatic relation support
  src/openvic-simulation/diplomacy/CountryRelation.cpp
  src/openvic-simulation/diplomacy/CountryRelation.hpp
  src/openvic-simulation/diplomacy/DiplomaticAction.cpp
  src/openvic-simulation/diplomacy/DiplomaticAction.hpp
Labels: enhancement

#326 Performance: reuse maps & PopValuesFromProvince
  src/openvic-simulation/economy/production/ArtisanalProducer.cpp
  src/openvic-simulation/economy/production/ArtisanalProducer.hpp
  src/openvic-simulation/map/MapInstance.cpp
  src/openvic-simulation/map/MapInstance.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/Pop.hpp
  src/openvic-simulation/pop/PopValuesFromProvince.cpp
  src/openvic-simulation/pop/PopValuesFromProvince.hpp
Labels: enhancement

#337 Round up income and expenses to handle inaccuracies
  src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
  src/openvic-simulation/economy/trading/GoodMarket.cpp
  src/openvic-simulation/economy/trading/MarketInstance.cpp
  src/openvic-simulation/economy/trading/MarketInstance.hpp
  src/openvic-simulation/pop/Pop.cpp
Labels: enhancement

#339 Minor BMP and IndexedMap cleanup
  src/openvic-simulation/types/IndexedMap.hpp
  src/openvic-simulation/utility/BMP.hpp
Labels: bug

#341 Reset pop income and expenses each tick
  src/openvic-simulation/pop/Pop.cpp
Labels: enhancement

#342 Add index to Technology struct
  src/openvic-simulation/research/Technology.cpp
  src/openvic-simulation/research/Technology.hpp
Labels: enhancement

#340 Add fixed point exponential functions for bases e and 2001 + LUT generator
  src/openvic-simulation/types/fixed_point/FixedPoint.hpp
  src/openvic-simulation/types/fixed_point/FixedPointLUT_2_16_EXP_2001.hpp
  src/openvic-simulation/types/fixed_point/FixedPointLUT_2_16_EXP_e.hpp
  src/openvic-simulation/types/fixed_point/lut_generator/exp_lut_generator.py
  src/openvic-simulation/types/fixed_point/lut_generator/sin_lut_generator.py
Labels: enhancement

#343 Fix artisan overspending
  src/headless/main.cpp
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/InstanceManager.hpp
  src/openvic-simulation/economy/production/ArtisanalProducer.cpp
  src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
  src/openvic-simulation/misc/SimulationClock.cpp
  src/openvic-simulation/misc/SimulationClock.hpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/Pop.hpp
Labels: bug

#344 Reuse GoodMarket vectors
  src/openvic-simulation/economy/trading/GoodMarket.cpp
  src/openvic-simulation/economy/trading/GoodMarket.hpp
  src/openvic-simulation/economy/trading/MarketInstance.cpp
  src/openvic-simulation/economy/trading/MarketInstance.hpp
  src/openvic-simulation/map/MapInstance.cpp
  src/openvic-simulation/map/MapInstance.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/utility/ParallelProcessorWithSharesValues.hpp
Labels: enhancement

#346 Make GameActionManager and its callback functions const
  src/openvic-simulation/InstanceManager.hpp
  src/openvic-simulation/misc/GameAction.cpp
  src/openvic-simulation/misc/GameAction.hpp
Labels: enhancement

#350 Fix occurrences of undefined behavior
  src/openvic-simulation/dataloader/NodeTools.cpp
  src/openvic-simulation/map/MapDefinition.cpp
  src/openvic-simulation/misc/Event.cpp
  src/openvic-simulation/testing/TestScript.cpp
  src/openvic-simulation/testing/TestScript.hpp
  src/openvic-simulation/testing/Testing.cpp
  src/openvic-simulation/testing/Testing.hpp
  src/openvic-simulation/types/Colour.hpp
  src/openvic-simulation/types/fixed_point/FixedPoint.hpp
  src/openvic-simulation/utility/StringUtils.hpp
Labels: bug, enhancement

#352 Add country tax properties
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
Labels: enhancement

#357 Fix bugs in threadpool
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/utility/ThreadPool.cpp
  src/openvic-simulation/utility/ThreadPool.hpp
Labels: bug
