Repository OpenVicProject/OpenVic-Simulation, pull requests merged in 2025-06, with the labels that each got.

#427 Negative tariffs
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/map/State.cpp
  src/openvic-simulation/map/State.hpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/Pop.hpp
Labels: enhancement, topic:economy

#445 Move const reference vectors to span
  src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
  src/openvic-simulation/economy/trading/GoodMarket.cpp
  src/openvic-simulation/economy/trading/GoodMarket.hpp
  src/openvic-simulation/history/ProvinceHistory.cpp
  src/openvic-simulation/map/MapDefinition.cpp
  src/openvic-simulation/map/MapDefinition.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/utility/BMP.cpp
  src/openvic-simulation/utility/BMP.hpp
Labels: enhancement, topic:codestyle

#447 Fix `Employee::get_pop() const` return type warning
  src/openvic-simulation/economy/production/Employee.hpp
Labels: bug

#448 Fix space/tab indentation mixing in MapDefinition
  src/openvic-simulation/map/MapDefinition.cpp
Labels: bug, topic:codestyle

#449 Move even more const reference vectors to span
  src/openvic-simulation/GameManager.cpp
  src/openvic-simulation/GameManager.hpp
  src/openvic-simulation/country/CountryDefinition.cpp
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/country/SharedCountryValues.cpp
  src/openvic-simulation/country/SharedCountryValues.hpp
  src/openvic-simulation/dataloader/Dataloader.cpp
  src/openvic-simulation/dataloader/Dataloader.hpp
  src/openvic-simulation/economy/BuildingType.cpp
  src/openvic-simulation/economy/GoodDefinition.cpp
  src/openvic-simulation/economy/production/ProductionType.cpp
  src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
  src/openvic-simulation/economy/production/ResourceGatheringOperation.hpp
  src/openvic-simulation/history/CountryHistory.cpp
  src/openvic-simulation/history/CountryHistory.hpp
  src/openvic-simulation/map/MapInstance.cpp
  src/openvic-simulation/map/MapInstance.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/ProvinceInstance.hpp
  src/openvic-simulation/map/State.cpp
  src/openvic-simulation/map/State.hpp
  src/openvic-simulation/map/TerrainType.cpp
  src/openvic-simulation/military/UnitType.cpp
  src/openvic-simulation/modifier/ModifierEffectCache.cpp
  src/openvic-simulation/politics/PoliticsInstanceManager.cpp
  src/openvic-simulation/politics/Rebel.cpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/Pop.hpp
  src/openvic-simulation/pop/PopType.cpp
  src/openvic-simulation/pop/PopValuesFromProvince.cpp
  src/openvic-simulation/pop/PopValuesFromProvince.hpp
  src/openvic-simulation/research/Technology.cpp
  src/openvic-simulation/types/Colour.hpp
  src/openvic-simulation/types/IndexedMap.hpp
  src/openvic-simulation/utility/ForwardableSpan.hpp
  src/openvic-simulation/utility/ThreadPool.cpp
  src/openvic-simulation/utility/ThreadPool.hpp
  src/openvic-simulation/utility/Utility.hpp
Labels: enhancement, topic:codestyle

#455 Fix benchmarks set_roots build error
  tests/benchmarks/src/dataloading/Dataloading.cpp
Labels: bug, topic:testing

#458 Fix `IndexedMap::operator()(size_t index)` build error
  src/openvic-simulation/types/IndexedMap.hpp
Labels: bug, topic:core

#459 Fix dangling reference crash in ThreadPool.cpp
  src/openvic-simulation/utility/ThreadPool.cpp
Labels: bug, crash, topic:core

#461 Graceful handling of provinces with multiple regions
  src/openvic-simulation/InstanceManager.cpp
  src/openvic-simulation/map/MapDefinition.cpp
  src/openvic-simulation/map/Region.cpp
  src/openvic-simulation/map/Region.hpp
  src/openvic-simulation/map/State.cpp
Labels: bug, topic:core

#463 Support multiple script nodes by combining them
  src/openvic-simulation/politics/Issue.cpp
  src/openvic-simulation/scripts/Condition.cpp
  src/openvic-simulation/scripts/Condition.hpp
  src/openvic-simulation/scripts/ConditionScript.cpp
  src/openvic-simulation/scripts/ConditionScript.hpp
  src/openvic-simulation/scripts/EffectScript.cpp
  src/openvic-simulation/scripts/EffectScript.hpp
  src/openvic-simulation/scripts/Script.hpp
Labels: bug, topic:core

#454 Add `PathingBase::get_iterator_by_id`
  src/openvic-simulation/pathfinding/PathingBase.hpp
Labels: enhancement, topic:ai

#466 Standardize _detail namespace names
  src/openvic-simulation/types/Vector.hpp
  src/openvic-simulation/types/VectorN.inc
  src/openvic-simulation/utility/Deque.hpp
  src/openvic-simulation/utility/ForwardableSpan.hpp
Labels: enhancement, topic:codestyle

#460 Add signal and signal_property based on sigslot
  src/openvic-simulation/types/CowPtr.hpp
  src/openvic-simulation/types/NullMutex.hpp
  src/openvic-simulation/types/Signal.hpp
  src/openvic-simulation/types/SpinMutex.hpp
  tests/src/types/Signal.cpp
Labels: enhancement, topic:core

#462 Add invalidation signals to pathfinding classes
  src/openvic-simulation/pathfinding/AStarPathing.hpp
  src/openvic-simulation/pathfinding/FringePathing.hpp
  src/openvic-simulation/pathfinding/PathingBase.hpp
  src/openvic-simulation/pathfinding/PointMap.cpp
  src/openvic-simulation/pathfinding/PointMap.hpp
Labels: enhancement, topic:ai

#469 Add ArmyAStarPathing for ArmyInstance pathing
  src/openvic-simulation/map/MapInstance.cpp
  src/openvic-simulation/map/MapInstance.hpp
  src/openvic-simulation/military/UnitInstanceGroup.hpp
  src/openvic-simulation/pathfinding/AStarPathing.cpp
  src/openvic-simulation/pathfinding/AStarPathing.hpp
Labels: enhancement, topic:ai, topic:military

#471 Fix build error for sorted_indexed_map_less_than
  src/openvic-simulation/types/IndexedMap.hpp
Labels: bug, topic:core

#472 Move key_span_type over explicit span in IndexedMap
  src/openvic-simulation/types/IndexedMap.hpp
Labels: enhancement, topic:codestyle

#467 Change fixed_point_t constants to constexpr variables
  src/openvic-simulation/country/CountryInstance.cpp
  src/openvic-simulation/country/CountryInstance.hpp
  src/openvic-simulation/country/SharedCountryValues.cpp
  src/openvic-simulation/defines/Define.cpp
  src/openvic-simulation/economy/production/ArtisanalProducer.cpp
  src/openvic-simulation/economy/production/ArtisanalProducerFactoryPattern.cpp
  src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
  src/openvic-simulation/economy/trading/BuyResult.hpp
  src/openvic-simulation/economy/trading/GoodMarket.cpp
  src/openvic-simulation/economy/trading/MarketInstance.cpp
  src/openvic-simulation/economy/trading/SellResult.hpp
  src/openvic-simulation/map/ProvinceInstance.cpp
  src/openvic-simulation/map/State.cpp
  src/openvic-simulation/map/TerrainType.cpp
  src/openvic-simulation/military/LeaderTrait.cpp
  src/openvic-simulation/military/UnitInstanceGroup.cpp
  src/openvic-simulation/misc/GameAction.cpp
  src/openvic-simulation/modifier/ModifierSum.cpp
  src/openvic-simulation/modifier/ModifierSum.hpp
  src/openvic-simulation/modifier/ModifierValue.cpp
  src/openvic-simulation/pathfinding/FringePathing.cpp
  src/openvic-simulation/pathfinding/PointMap.cpp
  src/openvic-simulation/pathfinding/PointMap.hpp
  src/openvic-simulation/pop/Pop.cpp
  src/openvic-simulation/pop/Pop.hpp
  src/openvic-simulation/pop/PopValuesFromProvince.cpp
  src/openvic-simulation/scripts/ConditionalWeight.cpp
  src/openvic-simulation/types/fixed_point/Atomic.hpp
  src/openvic-simulation/types/fixed_point/FixedPoint.hpp
  src/openvic-simulation/types/fixed_point/FixedPointMap.hpp
  tests/src/dataloader/NodeTools.cpp
  tests/src/pathfinding/PointMap.cpp
  tests/src/types/AtomicFixedPoint.cpp
  tests/src/types/FixedPoint.cpp
  tests/src/types/Vector2.cpp
  tests/src/types/Vector3.cpp
  tests/src/types/Vector4.cpp
Labels: enhancement, topic:codestyle
